apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            template: wait-20
          - name: b
            template: fails-on-purpose
          - name: c
            template: wait-10
          - name: d
            template: whalesay
            dependencies:
              - a
              - b
              - c
    - name: wait-20
      container:
        image: charliehpd/python-docker-20
    - name: wait-10
      container:
        image: charliehpd/python-docker-10
    - name: fails-on-purpose
      container:
        image: charliehpd/fails-on-purpose
        resources:
            limits:
              memory: 280Mi
              cpu: 200m
    - name: whalesay
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]